### ISSUE TITLE
Add some questions

### ISSUE THREAD

**Issue by KMSOMERS** [KMSOMERS/NeverHaveIEver100DaysChallenge#2]
More questions is always good, I would be grateful for questions added to the Arrays.xml file.

Questions to be added in the format below

<item>QUESTION HERE</item>

The app will then display the question as Never have I ever QUESTION HERE

Please keep the questions relevant to the category and multiple pull requests with a single question will be marked as spam going forward!

**Comment by CodeByAlex** [comment]
I can work on this

**Comment by rockydcoder** [comment]
The `weird` section has less questions. I can add more questions there.
