### ISSUE TITLE
Remove duplicate / similar questions

### ISSUE THREAD

**Issue by KMSOMERS** [KMSOMERS/NeverHaveIEver100DaysChallenge#8]
Currently the app has quite a lot of questions with some repeats or similar wording.

If you find two questions that are similar or repeats just remove one and commit.

**Comment by rockydcoder** [comment]
Hi, can I work on this?

**Comment by KMSOMERS** [comment]
Go ahead would be very useful for me!

**Comment by JulianJason** [comment]
Hi, I will work on this too

**Comment by MatheusMuriel** [comment]
Cloning

**Comment by adalbertobrant** [comment]
Hi where do I find the questions?

**Comment by dharmadev108** [comment]
i'd like to give it a go, is that ok?  :)
